import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero/Hero";
import HeroSection from "../components/Hero/Herosection";
import Introduction from "../components/Introduction/Introduction";
import Projects from "../components/Projects/Projects";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Codecression</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <div className=" "></div>
      <Introduction />
      <Projects />
    </>
  );
}
